name: Tests Calculator

on: push
jobs:
  run-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python 3.12.0
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.0'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Tests Calculator
        run: pytest